# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 853b5915c0f733d638daadea176f8480e07c1d1ec40457291b82ca31678df7ef53ac8390d39e4986899914f5b8d0388d23f1a6b33cd1efca54bd57504eb1c1fd

test:
  secret_key_base: 0b380ba8145521f8887d6d32844c0b91967249ba8ec928ba05a254d0f16b940de34e05468f1e92805007ae80112361a710912c1ae9b7ad6a62f0223438cfd871

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
